pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven { url "https://maven.architectury.dev" };
    }
}

rootProject.name = 'stuck_arrows_for_all'
include('common', 'fabric', 'forge')